package com.classes.Backend.Domain.activity;

public enum ActivityActionType {
    LOGIN,
    LOGIN_OTP,
    LOGOUT,
    TOKEN_REFRESH,
    STUDENT_REGISTERED,
    STUDENT_PROFILE_UPDATED,

    INSTITUTE_CREATED,
    INSTITUTE_ACTIVATED,
    INSTITUTE_DEACTIVATED,
    INSTITUTE_UPDATED,
    INSTITUTE_DELETED,
    INSTITUTE_VERIFIED,
    INSTITUTE_UNVERIFIED,
    INSTITUTE_FEATURED,
    INSTITUTE_UNFEATURED,

    COURSE_CREATED,
    COURSE_UPDATED,
    COURSE_DELETED,

    SUBMITTED_INQUIRY,
    BOOKED_DEMO,
    UNLOCKED_LEAD,

    BRANCH_CREATED,
    BRANCH_UPDATED,
    BRANCH_DELETED,

    FACULTY_CREATED,
    FACULTY_UPDATED,
    FACULTY_DELETED,

    RESULT_CREATED,
    RESULT_UPDATED,
    RESULT_DELETED,

    FACILITY_CREATED,
    FACILITY_UPDATED,

    FAQ_CREATED,
    FAQ_UPDATED,
    FAQ_DELETED,

    MEDIA_UPLOADED,
    MEDIA_DELETED,

    SUBMITTED_REVIEW,
    REVIEW_VOTED,
    BOOKMARKED,
    REMOVED_BOOKMARK,
    COMPARED_INSTITUTES,
    SEARCHED_INSTITUTES,
    VIEWED_INSTITUTE,
    VIEWED_COURSE,

    STAFF_ADDED,
    STAFF_REMOVED,
    STAFF_ROLE_CHANGED,

    CREDITS_GRANTED,
    CREDITS_DEDUCTED,
    TOP_UP_REQUESTED,
    TOP_UP_APPROVED,
    TOP_UP_REJECTED,
    FEATURED_PURCHASED,
    SUBSCRIPTION_CHANGED
}
